### PR TITLE
fix: Added new force_destroy variable to cloudbuild module.

### PR DESCRIPTION
**Pull request by lpezet**
This is a proposed fix for issue #146

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @lpezet!

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/examples/cloudbuild_enabled/README.md /tmp/tmp.gaJjQtWSFY/generate_docs/workspace/examples/cloudbuild_enabled/README.md
11a12
> | force\_destroy | If supplied, the logs and artifacts buckets will be deleted even while containing objects. | `bool` | `false` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/modules/cloudbuild/README.md /tmp/tmp.gaJjQtWSFY/generate_docs/workspace/modules/cloudbuild/README.md
61a62
> | force\_destroy | If supplied, the logs and artifacts buckets will be deleted even while containing objects. | `bool` | `false` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

**Comment by lpezet** [comment]
@apeabody Ah yes, thanks. I was looking for a way to update the doc.

**Comment by lpezet** [comment]
Shoot...build failed. What did I do wrong?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @lpezet!

**Pull request merged**
