### PR TITLE
updated tf (12.29) and validator (2020-09-24) versions

### PR DESCRIPTION
**Pull request by mikelaramie**
To fix issue #70 - Updated the versions of terraform 0.12 and terraform-validator to the latest versions

### CODE REVIEW

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR! @mikelaramie we can also replace the defaults here
https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/d09725f48054b2d0c08001b3650be7413d610c38/modules/cloudbuild/variables.tf#L122

**Comment by mikelaramie** [comment]
Oh, I didn't see those! I can update those as well; or do you think it's better in general to leave the defaults at an older version and let people modify it themselves?

**Comment by bharathkkb** [comment]
@mikelaramie I think it makes sense to update all defaults but will defer to @rjerrems

**Review by bharathkkb — APPROVED** [review]
LGTM

**Pull request merged**
