### PR TITLE
upgrade module version

### PR DESCRIPTION
**Pull request by ericyz**
The project-factory min support TF version is v0.13.0 now, so update the Terraform version used in Cloud Build module

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/cloudbuild/README.md /tmp/tmp.hQ7wBaCd2q/generate_docs/workspace/modules/cloudbuild/README.md
74,75c74,75
< | terraform\_version | Default terraform version. | `string` | `"0.12.29"` | no |
< | terraform\_version\_sha256sum | sha256sum for default terraform version. | `string` | `"872245d9c6302b24dc0d98a1e010aef1e4ef60865a2d1f60102c8ad03e9d5a1d"` | no |
---
> | terraform\_version | Default terraform version. | `string` | `"0.13.6"` | no |
> | terraform\_version\_sha256sum | sha256sum for default terraform version. | `string` | `"b0bb7c6a8ff6a81af7bcc8b6261f393e0a0b53900647a472a700bc25c7f4a262"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by rjerrems** [comment]
@ericyz thanks for the PR :) - it looks like the docker build is failing with these updated parameters. Can you verify that it is working as expected through a local run?

Also for consistency, can you please also update these files? (they help ensure the cloudbuild YAML and Dockerfile can still be used in isolation from the rest of the code)

https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/cloudbuild_builder/Dockerfile#L17

https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/cloudbuild_builder/cloudbuild.yaml#L30

**Comment by ericyz** [comment]
Thanks @rjerrems ! I used the wrong terraform hash and it's been updated now.

**Comment by rjerrems** [comment]
Looks like you need to regenerate docs again @ericyz

**Comment by rjerrems** [comment]
The other error looks like too many concurrent runs happening elsewhere, so should be ok once linting is fixed.

**Review by rjerrems — APPROVED** [review]

**Pull request merged**
