### PR TITLE
fix: downgrade minimum provider version

### PR DESCRIPTION
**Pull request by rjerrems**
Downgrade minimum provider version, to provider better compatibility with existing code bases using the module

### CODE REVIEW

**Comment by morgante** [comment]
This is fine, but I'm confused why we need to do this? No module should be setting a *maximum* version.

**Comment by rjerrems** [comment]
So this is in cases where people have fixed the provider version in their repo, to something below our minimum version. It caused a few problems with the example repo where the version was fixed. (and I had a couple pings from people using the version of example on master as well)

**Comment by morgante** [comment]
> So this is in cases where people have fixed the provider version in their repo, to something below our minimum version.

For the example repo, we should simply be increasing the provider version.

**Comment by rjerrems** [comment]
Yup we have done that (on develop), but this is just to decrease chances of other people having issues that are using it in there own code base. Not a huge issue.

**Pull request merged**
