### PR TITLE
chore: add example for encrypted tfstate bucket

### LINKED ISSUE #119: Add example and tests for encrypted state bucket with cmek
Now that CMEK is supported as of https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/115

We should add a usage example here https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/examples and tests to verify that this is working as expected.

FYI @imrannayer @bharathkkb

### PR DESCRIPTION
**Pull request by imrannayer**
Fix #119

### CODE REVIEW

**Comment by imrannayer** [comment]
@bharathkkb can u plz check why tests are failing?

**Comment by daniel-cit** [comment]
It looks like to be this issue https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1721

```
Error while installing hashicorp/google v4.75.0: open
/workspace/test/integration/tmp/.terraform/registry.terraform.io/hashicorp/google/4.75.0/linux_amd64/terraform-provider-google_v4.75.0_x5:
text file busy
}
    init.go:13: FatalError{Underlying: error while running command: exit status 1; 
        Error: Failed to install provider
        
        Error while installing hashicorp/google v4.75.0: open
        /workspace/test/integration/tmp/.terraform/registry.terraform.io/hashicorp/google/4.75.0/linux_amd64/terraform-provider-google_v4.75.0_x5:
        text file busy
        }
```

**Comment by imrannayer** [comment]
Pipeline timed out. Parallelize a few tasks.

**Comment by imrannayer** [comment]
@bharathkkb can you plz execute integration test again?

**Comment by imrannayer** [comment]
@bharathkkb added steps in integration test

**Pull request closed without merging**
