### PR TITLE
feat: add support for `included_files` and `ignored_files` of `google_cloudbuild_trigger`

### PR DESCRIPTION
**Pull request by jumpeiMano**
This PR adds support two options of `google_cloudbuild_trigger` resource.
- [`included_files`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#included_files)
- [`ignored_files`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#ignored_files)

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@jumpeiMano
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/tf_cloudbuild_workspace/README.md /tmp/tmp.oRp7wp4JiM/generate_docs/workspace/modules/tf_cloudbuild_workspace/README.md
38,62c38,62
< | Name                        | Description | Type                                                                                         | Default                       | Required |
< |-----------------------------|-------------|----------------------------------------------------------------------------------------------|-------------------------------|:--------:|
< | buckets\_force\_destroy     | When deleting the bucket for storing CloudBuild logs/TF state, this boolean option will delete all contained objects. If false, Terraform will fail to delete buckets which contain objects. | `bool`                                                                                       | `false`                       | no |
< | cloudbuild\_apply\_filename | Optional Cloud Build YAML definition used for terraform apply. Defaults to using inline definition. | `string`                                                                                     | `null`                        | no |
< | cloudbuild\_env\_vars       | Optional list of environment variables to be used in builds. List of strings of form KEY=VALUE expected. | `list(string)`                                                                               | `[]`                          | no |
< | cloudbuild\_plan\_filename  | Optional Cloud Build YAML definition used for terraform plan. Defaults to using inline definition. | `string`                                                                                     | `null`                        | no |
< | cloudbuild\_included\_files | Optional list. Changes affecting at least one of these files will invoke a build. | `list(string)`                                                                               | `[]`                          | no |
< | cloudbuild\_ignored\_files  | Optional list. Changes only affecting ignored files will not invoke a build. | `list(string)`                                                                               | `[]`                          | no |
< | cloudbuild\_sa              | Custom SA id of form projects/{{project}}/serviceAccounts/{{email}} to be used by the CloudBuild trigger. Defaults to being created if empty. | `string`                                                                                     | `""`                          | no |
< | cloudbuild\_sa\_roles       | Optional to assign to custom CloudBuild SA. Map of project name or any static key to object with project\_id and list of roles. | <pre>map(object({<br>    project_id = string<br>    roles      = list(string)<br>  }))</pre> | `{}`                          | no |
< | create\_cloudbuild\_sa      | Create a Service Account for use in Cloud Build. If false `cloudbuild_sa` has to be specified. | `bool`                                                                                       | `true`                        | no |
< | create\_state\_bucket       | Create a GCS bucket for storing state. If false `state_bucket_self_link` has to be specified. | `bool`                                                                                       | `true`                        | no |
< | diff\_sa\_project           | Set to true if `cloudbuild_sa` is in a different project for setting up https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#cross-project_set_up. | `bool`                                                                                       | `false`                       | no |
< | enable\_worker\_pool        | Set to true to use a private worker pool in the Cloud Build Trigger. | `bool`                                                                                       | `false`                       | no |
< | location                    | Location for build logs/state bucket | `string`                                                                                     | `"us-central1"`               | no |
< | prefix                      | Prefix of the state/log buckets and triggers planning/applying config. If unset computes a prefix from tf\_repo\_uri and tf\_repo\_dir variables. | `string`                                                                                     | `""`                          | no |
< | project\_id                 | GCP project for Cloud Build triggers, state and log buckets. | `string`                                                                                     | n/a                           | yes |
< | state\_bucket\_self\_link   | Custom GCS bucket for storing TF state. Defaults to being created if empty. | `string`                                                                                     | `""`                          | no |
< | substitutions               | Map of substitutions to use in builds. | `map(string)`                                                                                | `{}`                          | no |
< | tf\_apply\_branches         | List of git branches configured to run terraform apply Cloud Build trigger. All other branches will run plan by default. | `list(string)`                                                                               | <pre>[<br>  "main"<br>]</pre> | no |
< | tf\_cloudbuilder            | Name of the Cloud Builder image used for running build steps. | `string`                                                                                     | `"hashicorp/terraform:1.2.2"` | no |
< | tf\_repo\_dir               | The directory inside the repo where the Terrafrom root config is located. If empty defaults to repo root. | `string`                                                                                     | `""`                          | no |
< | tf\_repo\_type              | Type of repo | `string`                                                                                     | `"CLOUD_SOURCE_REPOSITORIES"` | no |
< | tf\_repo\_uri               | The URI of the repo where Terraform configs are stored. | `string`                                                                                     | n/a                           | yes |
< | worker\_pool\_id            | Custom private worker pool ID. Format: 'projects/PROJECT\_ID/locations/REGION/workerPools/PRIVATE\_POOL\_ID'. | `string`                                                                                     | `""`                          | no |
---
> | Name | Description | Type | Default | Required |
> |------|-------------|------|---------|:--------:|
> | buckets\_force\_destroy | When deleting the bucket for storing CloudBuild logs/TF state, this boolean option will delete all contained objects. If false, Terraform will fail to delete buckets which contain objects. | `bool` | `false` | no |
> | cloudbuild\_apply\_filename | Optional Cloud Build YAML definition used for terraform apply. Defaults to using inline definition. | `string` | `null` | no |
> | cloudbuild\_env\_vars | Optional list of environment variables to be used in builds. List of strings of form KEY=VALUE expected. | `list(string)` | `[]` | no |
> | cloudbuild\_ignored\_files | Optional list. Changes only affecting ignored files will not invoke a build. | `list(string)` | `[]` | no |
> | cloudbuild\_included\_files | Optional list. Changes affecting at least one of these files will invoke a build. | `list(string)` | `[]` | no |
> | cloudbuild\_plan\_filename | Optional Cloud Build YAML definition used for terraform plan. Defaults to using inline definition. | `string` | `null` | no |
> | cloudbuild\_sa | Custom SA id of form projects/{{project}}/serviceAccounts/{{email}} to be used by the CloudBuild trigger. Defaults to being created if empty. | `string` | `""` | no |
> | cloudbuild\_sa\_roles | Optional to assign to custom CloudBuild SA. Map of project name or any static key to object with project\_id and list of roles. | <pre>map(object({<br>    project_id = string<br>    roles      = list(string)<br>  }))</pre> | `{}` | no |
> | create\_cloudbuild\_sa | Create a Service Account for use in Cloud Build. If false `cloudbuild_sa` has to be specified. | `bool` | `true` | no |
> | create\_state\_bucket | Create a GCS bucket for storing state. If false `state_bucket_self_link` has to be specified. | `bool` | `true` | no |
> | diff\_sa\_project | Set to true if `cloudbuild_sa` is in a different project for setting up https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#cross-project_set_up. | `bool` | `false` | no |
> | enable\_worker\_pool | Set to true to use a private worker pool in the Cloud Build Trigger. | `bool` | `false` | no |
> | location | Location for build logs/state bucket | `string` | `"us-central1"` | no |
> | prefix | Prefix of the state/log buckets and triggers planning/applying config. If unset computes a prefix from tf\_repo\_uri and tf\_repo\_dir variables. | `string` | `""` | no |
> | project\_id | GCP project for Cloud Build triggers, state and log buckets. | `string` | n/a | yes |
> | state\_bucket\_self\_link | Custom GCS bucket for storing TF state. Defaults to being created if empty. | `string` | `""` | no |
> | substitutions | Map of substitutions to use in builds. | `map(string)` | `{}` | no |
> | tf\_apply\_branches | List of git branches configured to run terraform apply Cloud Build trigger. All other branches will run plan by default. | `list(string)` | <pre>[<br>  "main"<br>]</pre> | no |
> | tf\_cloudbuilder | Name of the Cloud Builder image used for running build steps. | `string` | `"hashicorp/terraform:1.2.2"` | no |
> | tf\_repo\_dir | The directory inside the repo where the Terrafrom root config is located. If empty defaults to repo root. | `string` | `""` | no |
> | tf\_repo\_type | Type of repo | `string` | `"CLOUD_SOURCE_REPOSITORIES"` | no |
> | tf\_repo\_uri | The URI of the repo where Terraform configs are stored. | `string` | n/a | yes |
> | worker\_pool\_id | Custom private worker pool ID. Format: 'projects/PROJECT\_ID/locations/REGION/workerPools/PRIVATE\_POOL\_ID'. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@jumpeiMano
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jumpeiMano
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@jumpeiMano
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @jumpeiMano

**Pull request merged**
