### PR TITLE
fix: updates to address tflint and CFT 1.10

### PR DESCRIPTION
**Pull request by apeabody**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_tflint
 Failed TFlint check. More details below. 
 ```bash 
Checking for tflint
Working in . ...
9 issue(s) found:
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: List items should be accessed using square brackets (terraform_deprecated_index)
  on main.tf line 28:
  28:   seed_org_depends_on        = try(google_folder_iam_member.tmp_project_creator.0.etag, "") != "" ? var.org_id : google_organization_iam_member.tmp_project_creator.0.org_id
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_index.md
Warning: Missing version constraint for provider "random" in "required_providers" (terraform_required_providers)
  on main.tf line 31:
  31: resource "random_id" "suffix" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_required_providers.md
Notice: `key_rotation_period` variable has no description (terraform_documented_variables)
  on variables.tf line 198:
 198: variable "key_rotation_period" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_documented_variables.md
Warning: `kms_prevent_destroy` variable has no type (terraform_typed_variables)
  on variables.tf line 203:
 203: variable "kms_prevent_destroy" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
tflint failed . 
Working in ./examples/cloudbuild_enabled ...
tflint passed ./examples/cloudbuild_enabled 
Working in ./examples/simple ...
tflint passed ./examples/simple 
Working in ./examples/simple-folder ...
tflint passed ./examples/simple-folder 
Working in ./examples/tf_cloudbuild_builder_simple ...
tflint passed ./examples/tf_cloudbuild_builder_simple 
Working in ./examples/tf_cloudbuild_source_simple ...
tflint passed ./examples/tf_cloudbuild_source_simple 
Working in ./examples/tf_cloudbuild_workspace_simple ...
tflint passed ./examples/tf_cloudbuild_workspace_simple 
Working in ./examples/tf_cloudbuild_workspace_simple/files ...
tflint passed ./examples/tf_cloudbuild_workspace_simple/files 
Working in ./modules/cloudbuild ...
4 issue(s) found:
Warning: Missing version constraint for provider "random" in "required_providers" (terraform_required_providers)
  on main.tf line 28:
  28: resource "random_id" "suffix" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_required_providers.md
Warning: data "google_organization" "org" is declared but not used (terraform_unused_declarations)
  on main.tf line 32:
  32: data "google_organization" "org" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_unused_declarations.md
Warning: Missing version constraint for provider "time" in "required_providers" (terraform_required_providers)
  on main.tf line 105:
 105: resource "time_sleep" "impersonate_propagation" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_required_providers.md
Warning: Missing version constraint for provider "null" in "required_providers" (terraform_required_providers)
  on main.tf line 265:
 265: resource "null_resource" "cloudbuild_terraform_builder" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_required_providers.md
tflint failed ./modules/cloudbuild 
Working in ./modules/tf_cloudbuild_builder ...
5 issue(s) found:
Warning: Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)
  on cb.tf line 28:
  28:     "_TERRAFORM_FULL_VERSION"  = "${local.tf_full_version}",
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_interpolation.md
Warning: Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)
  on cb.tf line 29:
  29:     "_TERRAFORM_MINOR_VERSION" = "${local.tf_minor_version}",
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_interpolation.md
Warning: Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)
  on cb.tf line 30:
  30:     "_TERRAFORM_MAJOR_VERSION" = "${local.tf_major_version}",
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_deprecated_interpolation.md
Warning: `dockerfile_repo_dir` variable has no type (terraform_typed_variables)
  on variables.tf line 105:
 105: variable "dockerfile_repo_dir" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
Warning: `dockerfile_repo_type` variable has no type (terraform_typed_variables)
  on variables.tf line 110:
 110: variable "dockerfile_repo_type" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
tflint failed ./modules/tf_cloudbuild_builder 
Working in ./modules/tf_cloudbuild_source ...
tflint passed ./modules/tf_cloudbuild_source 
Working in ./modules/tf_cloudbuild_workspace ...
2 issue(s) found:
Warning: `tf_repo_dir` variable has no type (terraform_typed_variables)
  on variables.tf line 140:
 140: variable "tf_repo_dir" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
Warning: `tf_repo_type` variable has no type (terraform_typed_variables)
  on variables.tf line 145:
 145: variable "tf_repo_type" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_typed_variables.md
tflint failed ./modules/tf_cloudbuild_workspace 
Skipping ./test/fixtures/cloudbuild_enabled
Skipping ./test/fixtures/simple
Skipping ./test/fixtures/simple-folder
Skipping ./test/setup
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
@bharathkkb - `tflint` requires provider minimum versions, so it appears this will now need to be a breaking change.  Any thoughts on their "inital" versions, or does this look good?

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
